--- 
title: "Public Finance"
author: "Jerome Dumortier"
date: "`r format(Sys.time(),'%d %B %Y')`"
output: pdf_document
site: bookdown::bookdown_site
---

# Preface
This book serves as an introduction to public finance and budgeting. At the end of each chapter are exercises to practice the concepts covered. The last chapter provides case studies, which require more in-depth analysis than the exercises. This book is continuously updated, which is one of the advantages of publishing on GitHub. The chapters also include YouTube videos and the channel is titled [Economics, Statistics, and Public Finance](https://www.youtube.com/@econstatspublicfinance). Links to specific videos are included in the respective chapters as well. There are also [formatting instructions](https://github.com/jrfdumortier/publicfinance/blob/main/AssignmentFormatting.pdf) regarding the homework assignments and case studies.

## Book Overview
The book is subdivided into five parts of varying length: (1) Introduction and role of government in the economy, (2) recurrent budgets, (3) capital budgets, (4) government revenue, and (5) debt management and forecasting.

**Introduction and role of government in the economy:** This part serves as an introduction to government finance and budgets. The topics covered in this chapter are (1) the size of federal expenditures (outlays) and revenue and (2) the role of government in the economy. A large emphasize of the chapter is on the purpose of taxation and government intervention in the economy. Topics such as externalities, public goods, and imperfect competition (commonly referred to as market failures) are covered that all justify (to a certain degree) government's role in the economy. It also covers economic stabilization and redistribution as reasons for government interventino. To better understand this and the remaining chapter(s), you should watch the video [Monetary Values over Time](https://youtu.be/t2bxcZF4pq4), which covers real and nominal prices. 

**Basics of Budget Preparation:** The focus of this chapter is on recurrent budgets that cover current year expenditures with current year revenue. A recurrent budget is different from a capital budgeting, which is covered later in the book. The goal of a recurrent budget is to ensure that the government's income matches its spending and thus, promotes fiscal responsibility. We cover the budgeting process, which typically involves a cycle that includes budget preparation, review, approval, and execution. This ensures that each phase is planned and scrutinized before implementation, allowing for effective management of public funds.

**Budgeting in the United States**: This chapter covers aspects of Federal, state, and local budgets specific to the United States. In the federal budgeting process, several important elements come into play. Institutions, audits, and evaluations are critical for ensuring transparency and accountability throughout the process. Appropriation bills are required for discretionary spending, which funds specific programs and services. Meanwhile, mandatory spending, such as Social Security and Medicare, does not require appropriation bills, as it is governed by existing laws.

**Budget Methods and Format:** Budget methods and formats vary depending on the needs of the government or institution. Budgets are often classified by categories such as functions, programs, or departments. Cost analysis is essential to ensure that resources are used efficiently and that decisions are based on a thorough understanding of the financial impact. The budget format typically includes examples and breakdowns to show how funds are allocated across different areas, ensuring clarity in the decision-making process.

**Cost Analysis**: To prepare a budget, institutions need to know the cost associated with service provision. This chapter covers cost accounting and estimation as well as cost allocation.

**Capital Budgeting**: Purchasing assets that are used multiple years (e.g., bridges, public school buildings, infrastructure in general) require assessment of future cost and benefits, which are covered in this chapter. The characteristics of capital assets is that (1) their useful life is more than one year, (2) the expenditure is non-recurring, (3) the expenditure is usually very large (e.g., infrastructure projects such as bridges or airports).
- Usually very large expenditure

**Government Revenue**: Compared to the previous chapters, which focus on the expenditure side of government activities, this chapter introduce the revenue side. General aspects of taxation such as equity, adequacy of revenue generation, the ability to collect revenue, and economic effects are covered. The various revenue generating activities presented are income taxes (i.e., taxes on individual and corporate incomes), taxes on goods and services (e.g., sales tax, fuel tax), property taxes, and other revenue sources (e.g., driver's license fees, state lotteries). Property taxes represent the majority of revenue for local governments and are spent locally on on education or public safety. At the state and local level, governments rely on three main sources of revenue: taxes, federal aid, and borrowing. These sources enable them to fund services and infrastructure projects.

**Debt management and forecasting:** At the federal level, it is important to distinguish between a deficit or surplus and debt. A deficit occurs when the government's outlays in a given fiscal year exceed its revenues, while a surplus arises when revenues exceed expenditures. In contrast, debt refers to the total amount of money the government owes, accumulated over years of deficits. A key aspect of borrowing involves bonds. When a government or entity issues a bond, it commits to paying the bondholder regular interest and repaying the principal at a future date, known as the maturity date. There are various types of bonds, and their values fluctuate based on interest rates, market demand, and the creditworthiness of the issuer.

**Deficit and debt management** involve strategies to handle both short-term fiscal imbalances and long-term accumulated debt. This ensures that governments can meet their financial obligations while maintaining economic stability.

## Data Sources
The intention of this book is to provide up-to-date data with each iteration. The book also places a very high importance of data credibility and only information from reputable sources are used. The focus is on objective and unbiased data from the original source. The following presents some of those data sources.

**Congressional Budget Office (CBO):** The CBO is associated with the legislative branch and publishes reports on a plethora of budgetary topics such as the [CBO Long Term Budget Analysis](https://www.cbo.gov/topics/budget/long-term-budget-analysis) or the cost of the [Coast Guard's Polar Security Cutter](https://www.cbo.gov/publication/60170). Of course, the long-term budget analysis is of great interest to stakeholders since it quantifies federal revenues and expenditures given current policies and macroeconomic projections. Those projections may not always be accurate but can serve a guidance for policy making. For example, in the [2002 CBO Projections (January 2002) The Budget and Economic Outlook: Fiscal Years 2003-2012](https://www.cbo.gov/sites/default/files/107th-congress-2001-2002/reports/senate.pdf), the projected debt held by the public as a percentage of GDP in 2012 was estimated to be 7.4\%, which was 69.4\% in reality ([Source](https://fred.stlouisfed.org/series/FYPUGDA188S)). Significant discrepancy between projection and reality can occur due to policy changes and unforeseen shocks such as tax cuts, homeland security, 2001 economic downturn, 2008 great recession, stimulus spending (all in the 2000's), or COVID-19.

**Office of Management and Budget (OMB):** Many data series associated with the federal budget are obtained from the White House's [OMB](https://www.whitehouse.gov/omb/).

**Federal Reserve Economic Data (FRED):** A data source extensively used throughout this book is the [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/) of the St. Louis Fed. The above mentioned data series regarding the debt held by the public as a percentage of GDP is obtained from FRED.

An additional data source for U.S. data is the [U.S. Census Bureau](https://www.census.gov/).

International organizations such as the International Monetary Fund (IMF), the World Bank, or the Organisation for Economic Co-operation and Development (OECD) provide data for all countries on important economic indicators. For example, data on [general government gross debt as a percentage of GDP](https://www.imf.org/external/datamapper/GGXWDG_NGDP@WEO/OEMDC/ADVEC/WEOWORLD) is provided by the IMF. The OECD compares the [tax revenue as a percent of GDP](https://data.oecd.org/tax/tax-revenue.htm) among member nations.

For the European Union (EU), the main data source is [EUROSTAT](https://ec.europa.eu/eurostat). The following are two examples:

- [General government deficit/surplus](https://ec.europa.eu/eurostat/databrowser/view/tec00127/default/table?lang=en)
- [General government gross debt](https://ec.europa.eu/eurostat/databrowser/view/sdg_17_40/default/table?lang=en)
