# Other Revenue Sources
The previous chapters have covered important revenue sources such as income taxes, consumption taxes, and property taxes. This chapter outlines other revenue sources such as user charges (i.e., purchasing a government service or good) and license fees (i.e., purchasing the right to engage in a regulated activity). There are also a YouTube [video](https://youtu.be/IE1ozcrTkuY?si=kxA-rGpmbPogdeFM) and [slides](https://github.com/jrfdumortier/slidespublicfinance/blob/main/OtherRevenueSources.pdf) associated with this chapter.

User charges refer to prices set by the government for services that are publicly provided and voluntarily purchased by individuals, such as fares for public transit. License fees on the other hand involve the sale of permits that allow individuals or entities to engage in activities that are otherwise restricted or prohibited. Examples of license fees are for driver licenses, hunting, selling alcohol. This chapter also covers price discrimination which can be based on the demographics of the consumers (e.g., seniors, students) or origin of the consumer (e.g., in-state/county or out-of-state/county residents). For example, Eagle Creek Park in Indianapolis charges a different fee for residents of Marion County. Note that there are many other charges by the government for a variety of services. Sanitation charges cover services such as trash collection, landfill use, and sewage management. Public utilities (e.g., water and electricity) involve fees related to meters, connection, and consumption. Transportation and parking fees include fares for subways and buses, tolls for bridges and roads, landing and departure fees at transportation hubs, and parking fees at meters or in lots. Parks and recreation charges apply to amenities like public golf courses and permits for using tennis courts.

```{r,echo=FALSE,fig="Revenue of license taxes by category for 2021 and selected states."}
soi  = c("CA","TX","FL","NY","PA","IL","OH","GA","NC","IA")
df   = subset(stc,stcgroup=="License Taxes" & year==2021 & base=="Real" & state %in% soi)
df$stcname[which(df$stcname=="Occupation and Business")] = "Business"
df$stcname[which(df$stcname=="Corporations")] = "Business"
ggplot(df,aes(fill=stcname,y=value,x=state))+geom_bar(position="fill",stat="identity")+theme_bw()+
     ylab("Share of Lic. Tax Revenue")+theme(axis.title.x=element_blank(),legend.title=element_blank(),
                                                legend.position="bottom")+
     scale_fill_brewer(palette="Paired")
```

There are some equity issues associated with user charges since those charges usually do not take into account income and everyone pays the same charge (except in the case of price discrimination) and thus, user charges are regressive.

## User Charges
Beneficiaries of certain public goods or services can often be identified at the individual level, allowing charges linked to frequency or volume of usage. This approach can help controlling the consumption with the possibility of price adjustments during periods of high (peak) demand. An example of such peak pricing would be raising toll fees during congestion as used on Interstate 15 in San Diego. Tolls are adjusted in real-time by 25 cents as frequently as every 6 minutes to improve traffic flow. Other examples include fees for using a city’s recreation facilities or parking. An important aspect is the prevention of non-payers from accessing the good or service (i.e. eliminating free riders). For this to work, exclusion must be achievable in a cost-effective manner. In general, user fees are the closest financing mechanism in the public sector that mirrors private sector pricing.

Services must be measurable (i.e. able to be quantified), excludable (i.e., restricted to paying users), and provide individual benefits to be suitable for user charges. There are also a variety of reasons to impose user charges. It reduces the reliance on tax revenue, encourages resource conservation, and helps manage overconsumption (e.g., congestion charges for roads). User charges also align with the benefits principle and allows governments to extend charges to non-residents that use the service.

User charges offer advantages and disadvantages to the government and individuals. On one hand, user charges provide an additional revenue source and enable the tracking of service demand, which may lead to an improvement in operating efficiency. They also enhance financing equity for selected  services (e.g., recreational) due to broad usage (e.g., non-residents, tax-exempt entities/individuals) shifting the financial burden away from local taxpayers. On the other hand, some services provide benefits that extend beyond the immediate recipient (e.g., create a positive externality), as seen with sanitation, meaning that user charges may not capture the full societal value of these services. Additionally, user charges can create a regressive financial burden, disproportionately affecting lower-income individuals. Denying essential services to non-payers can also be problematic, especially for necessities like water, electricity, and natural gas.

## Design Considerations for User Charges
The feasibility of implementing a user charge depends on the ability to measure the service's output. This involves determining the appropriate type of output measure and ensuring that the measure is practical and cost-effective. Effective exclusion of non-payers is also essential, and the system should minimize opportunities for charge avoidance. The extent to which a user charge covers the cost of a service is influenced by objectives related to resource conservation and/or externalities. In the case of positive externalities (e.g. public health), governments may be inclined to have a lower fee (compared to the cost of the service) whereas for negative externalities, cost may be higher. The setting of the user charge should align consumption with broader societal goals, either by promoting or discouraging certain behaviors.

### Price Discrimination and User Charges
User charges can vary with (1) usage volume, (2) time of use, and/or (3) type of user. When charges increase with higher usage, it reflects a constant or rising marginal cost per unit, promoting conservation by discouraging excessive consumption. Conversely, if charges decrease with higher usage, it can encourage higher use. Charges can also vary by time of use (e.g., day, week, month) depending on demand patterns. For services with significant demand variation or limited capacity at peak times, adjusting charges can help manage congestion. The feasibility and cost of adding capacity during peak times also influence this approach. For example, a zoo might vary its entry fees by season or time of day, charging higher prices during peak periods to encourage more uniform attendance. 

User charges can also vary by the type of user, reflecting different pricing strategies for specific groups like seniors, children, or students. This differentiation considers variations in unit costs among user types and/or differences in willingness-to-pay. It is also possible that the presence of externalities associated with certain groups can justify differentiated charges. In some industries, price discrimination based on varying willingness-to-pay allows for higher profits by tailoring prices to different users. Differentiation based on the ability-to-pay is another approach that is motivated by equity considerations. This can involve means-testing to adjust charges according to financial capacity, especially when services are essential. However, applying user charges can sometimes create a regressive impact, placing a greater financial burden on lower-income users who may need these services.

Non-residents may be subject to different pricing structures to account for the higher costs associated with providing services to them. Since public services are often subsidized by general taxes paid by residents, differentiated charges ensure that non-residents contribute fairly to their usage. This pricing approach also helps preserve adequate capacity for residents by discouraging excessive non-resident use, similar to the distinction made between in-state and out-of-state tuition fees at public universities. An example of this practice is seen at the Memphis Zoo where it is called "Tennessee Tuesday":

> The Memphis Zoo allows free general admission to Tennessee residents with ID on Tuesday afternoons from 2 p.m. to close. 

This policy provides residents with a benefit funded by local resources, while non-residents continue to pay regular admission fees, aligning with the principle of local tax support for public services.

A two-part user charge divides the total fee into a fixed component and a variable component, where the full charge is the sum of a fixed fee and a charge per unit of usage. The fixed fee is often linked to depreciation costs for capital components of the service and other fixed costs, distributed across all users. The variable charge per unit reflects the unit cost of non-fixed expenses, aligning charges more closely with actual usage. The primary advantage of a two-part used charge approach is that it allows for full cost recovery while promoting efficient consumption decisions, as users pay directly based on their usage level. However, a notable drawback is that the fixed fee portion of the charge tends to be regressive, disproportionately impacting lower-income users, as they pay the same fixed amount regardless of usage.

## Evaluation of User Charges
Imposing user charges on public goods and services allows the government to measure demand as users express their preferences through their willingness-to-pay for the good or service. As long as demand exists, the service can be continually provided without restrictions, even during periods of fiscal shortfall, ensuring stability in service delivery. Agencies can also respond to consumer demand since the process of providing these services operates independently of political considerations. By removing the need for legislative bodies to appropriate funds, user charges minimize political influence, allowing agencies to focus on meeting actual demand rather than relying on budgetary allocations. User charges have implications for both efficiency and equity. 

In terms of efficiency, user charges influence economic decisions, such as reducing the frequency of visits to a zoo. However, they may also enhance the operating efficiency of service providers, as revenues are more closely tied to actual demand and usage. According to the benefits principle, user charges are aligned with the idea that those who benefit from a service should contribute to its costs. This contrasts with broad-based taxes like property taxes, where the benefit principle may not apply as directly, particularly for services like a zoo that only certain residents may use.

In terms of horizontal equity, user charges may create disparities among households with similar ability-to-pay. Households that do not use the service are not burdened by the charge, which can be beneficial, but for those who do use it, the financial burden might become significant. This could potentially exclude households from accessing certain services due to cost. In terms of vertical equity, user charges can be regressive, as lower-income users may have a higher relative burden compared to wealthier individuals, given that the cost does not vary proportionately with income.

User charges can theoretically provide adequate financing for operations if they are set to fully cover the cost of service provision. Depending on the elasticity, user charges can also generate more revenue with higher economic growth. For user charges to keep pace with economic growth, revenue would need to increase even without adjustments to the charge rates, which may not always be the case if demand does not grow proportionally. Ideally, user charges should generate a relatively stable revenue stream; however, demand-based fluctuations can introduce volatility. For example, in economic downturns, usage of certain public services may decline, leading to reduced revenues from user charges and impacting their stability as a funding source.

## License Fees
Licenses serve as regulatory tool for specific activities, such as driving and the sale of alcohol. Typically, they are charged at a flat rate, although fees may vary depending on the type of activity. While a license grants permission to engage in an activity, it does not constitute the purchase of a service or good. There are different types of licenses based on their purpose. Regulatory licenses are often restrictive and require  inspections to ensure compliance with standards, as seen with alcohol licenses. Revenue licenses, on the other hand, are issued primarily for generating income, with minimal restrictions and no inspection requirements, and are generally available to all applicants.